### ISSUE TITLE
dir file for contents of opaexport-conv.s3.amazonaws.com/ bucket  (directory listing) - Manifester

### ISSUE THREAD

**Issue by ghstern** [usnationalarchives/nara-scripts#3]
For importing the partner images we need to map the digital object file locations to the descriptions.

These are scattered in an s3 bucket:
opaexport-conv.s3.amazonaws.com/

A previous contractor wrote a script that basically performs an old DOS "dir" directory listing, but it is slow and not always "accurate," (the file bombs out, and we've been running until we get three files of the same file size.

I have an exe file, but I can't save it here. Let me know if you want to get access to it.

The Search-bat.txt [bat] file might shed some clues?

```
@ECHO off
cls
GOTO Getkey

:Getkey
set /p SVER=What is the keyword search? 
ECHO .

if "%SVER%"=="" GOTO Fail
@ECHO ON

s3_manifester.exe -bucket opaexport-conv -akid [ACCESS KEY] -seckey [SECRET ACCESS KEY]+ -csv yes -search %SVER%

@ECHO OFF
ECHO .
pause
exit

:Fail
ECHO No Keyword
ECHO .
GOTO :Getkey
```

Here is an example of the output.
[opaexport-conv_m2062_1470425366-csv.xlsx](https://github.com/usnationalarchives/nara-scripts/files/569520/opaexport-conv_m2062_1470425366-csv.xlsx)

We then run the python scripts that you guys have been working on.

Please let me know if this makes or doesn't make any sense.

Thanks!
-Gary

**Comment by DominicBM** [comment]
@clingerman @ghstern Do you have a good search term for me to test with? (i.e., something where you could tell from the results that it looks right)

**Comment by clingerman** [comment]
@DominicBM Try "M1091" - that one's not too big

**Comment by clingerman** [comment]
Closing, satisfied by [s3_file_list.py](https://github.com/usnationalarchives/partner-data-transform/blob/master/s3_file_list.py) in partner-data-transform repo
